---
- name: Preparing packages 
  hosts: server
  remote_user: root

  tasks:

    - name: Updating packet lists
      apt:
        name: "*"
        state: latest

    - name: Installing required packages
      package:
        name:
          - apt-transport-https
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - ufw
          - fail2ban
          - python3
          - pip

    - name: PIP install docker
      pip:
        name: docker

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

#    - name: Adding Dockers Repository
#      lineinfile:
#        path: /etc/apt/sources.list.d/docker.list
#        line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable'
#        state: present 
#        create: yes

#    - name: Add signing key
#      ansible.builtin.apt_key:
#        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
#        state: present

#    - name: Adding Dockers GPG Key
#      shell:
#        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg	

#    - name: Adding Dockers GPG Key
#      apt_key:
#        url: http://download.docker.com/linux/debian/gpg

    - name: Updating modified packet lists
      apt:
        name: "*"
        state: latest

    - name: Installing Docker-engine and CLI components
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
    
    - name: Add Issue.net
      blockinfile:
        path: /etc/issue.net
        block: |
          ********************************************************************
          *                                                                  *
          * This system is for the use of authorized users only.  Usage of   *
          * this system may be monitored and recorded by system personnel.   *
          *                                                                  *
          * Anyone using this system expressly consents to such monitoring   *
          * and is advised that if such monitoring reveals possible          *
          * evidence of criminal activity, system personnel may provide the  *
          * evidence from such monitoring to law enforcement officials.      *
          *                                                                  *
          ********************************************************************

    - name: Enable Issue.net within sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#Banner none'
        insertafter: '^#Banner none'
        line: Banner /etc/issue.net
