---
- name: Preparing packages 
  hosts: server
  remote_user: root

  tasks:

    - name: Updating packet lists
      apt:
        name: "*"
        state: latest

    - name: Installing required packages
      package:
        name:
          - apt-transport-https
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - ufw
          - fail2ban
          - python3
          - pip

    - name: PIP install docker
      pip:
        name: docker

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Updating modified packet lists
      apt:
        name: "*"
        state: latest

    - name: Installing Docker-engine and CLI components
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
    
