---
- name: Setup UFW
  hosts: server
  gather_facts: false
  remote_user: root

  tasks:

  - name: Default deny 
    shell:
      cmd: ufw default deny

  - name: Enable Logging 
    shell:
      cmd: ufw logging on 

  - name: Allow 80 Port TCP
    community.general.ufw:
      rule: allow
      proto: tcp
      to_port: '80'

  - name: Allow 22 Port TCP
    community.general.ufw:
      rule: allow
      proto: tcp
      to_port: '22'

  - name: Enable & start UFW
    community.general.ufw:
      state: enabled 
