---
- name: Start Docker Container apache-httd
  hosts: server
  gather_facts:false
  remote_user: root

  tasks:

    - name: Starting the Container...
      docker_container:
        name: apache-httpd
        state: started
