---
- name: Stop Docker Container apache-httd
  hosts: server
  gather_facts: false
  remote_user: root

  tasks:

    - name: Stopping the Container...
      docker_container:
        name: apache-httpd
        state: stopped
