---
- name: Delete Docker Container apache-httd
  hosts: server
  gather_facts:false
  remote_user: root

  tasks:

    - name: Deleting the Container...
      docker_container:
        name: apache-httpd
        state: absent
